//! Raw FFI bindings to the vendored libsrtp2 C library, generated by
//! `bindgen` in `build.rs` and emitted to `OUT_DIR`. See `build.rs` for the
//! compile defines (OpenSSL crypto backend) and allowlist. This module is the
//! low-level seam; the safe wrapper lives in [`crate::srtp_transport`].

#![allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    dead_code,
    unreachable_pub,
    missing_docs
)]

include!(concat!(env!("OUT_DIR"), "/srtp_bindings.rs"));
